##MySQl
spring:
  datasource:
    url: jdbc:mysql://localhost/walloniatacoscloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: walloniatacosuser 
    password: tacospassword
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
logging:
  level:
    wallonia: DEBUG
greeting: 
  welcome: You are using ${spring.application.name}.
taco:
   orders:
     pageSize: 10
     
---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:oracle://localhost/walloniatacoscloud
    username: walloniatacosuser
    password: tacospassword
    
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      
logging:
  level:
    wallonia: WARN